fastlane_version "2.2.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # update_fastlane
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
    danger
  end

  lane :fabric do |values|

    match( type: "adhoc", readonly: true)
    gym(scheme: 'Jkpls', export_method: 'ad-hoc')

    crashlytics(api_token: 'b242a59cce52fc9fbdd371946e844c0309b98098',
             build_secret: 'e045cfab8eee6cbc4d85a30ca36d45e9564857562cf69750c92f63bd0c12f3c5',
             notes: changelog_from_git_commits(include_merges: false),
             notifications: true)
  end


  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Jkpls") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Jkpls") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
